### ISSUE TITLE
Provide a library for 64bit Ubuntu 22.04

### ISSUE THREAD

**Issue by kirillmorozov** [doosan-robotics/API-DRFL#11]
Ubuntu 22.04 was released this April, can you provide DRFL library for this distro for those who want to use the latest and greatest software?

**Comment by doosan-robotics** [comment]
There are currently no plans for that matter.

**Comment by doosan-robotics** [comment]
@kirillmorozov 
We will notify you again when the ubuntu 22.04 LTS library is available.

**Comment by gavanderhoorn** [comment]
Just curious to see whether there have been any updates here @doosan-robotics?

Would you happen to have a version of `API-DRFL` that's compatible with `22.04`?
