### ISSUE TITLE
registering / setting a tool 

### ISSUE THREAD

**Issue by weinmama** [doosan-robotics/API-DRFL#12]
Hello,

what are the conditions under which a tool incl. the tool weight and a center of gravity can be registered on the controller?
Our observation is that the robot (H2017) tells Ok (add_tool / set_tool) and then the tool's weight may not be applied. This means that we cannot use the Teach-mode to hand-guide the robot for example.
In situations, when the tool weight is not registered in the system there may be a Log-Alarm event e.g. 1111 but, this is not the general case when something went wrong.
We found out that the 1111 alarm happens on registration, when the robot needs mastering for example. - Therefore is it impossible to register a tool when the mastering is needed? What might be other cases, that make a tool registration impossible?

Under which circumstances a tool registration should be successful? What is the way to do it? 

Thank you.

**Comment by kirillmorozov** [comment]
Hello @weinmama. Take a look at #5 where I'm basically asking Doosan team about the proper way to set tool/workpiece weight.

**Comment by doosan-robotics** [comment]
@weinmama 
In situations where mastering is required, tool registration is not possible. Please try again after executing the homing command.

**Comment by doosan-robotics** [comment]
@weinmama 
Please reopen the issue if you encounter additional issues.
