### ISSUE TITLE
Realtime API - Packet loss issue

### ISSUE THREAD

**Issue by robb19y** [doosan-robotics/API-DRFL#13]
Dear Doosan Robotics Team,
we are using realtime API to achieve some advanced control scenario.

We were able to setup a Linux Xenomai environment and use the API to control the robot.

However we noted that when using small control step (1 ms), robot apparently loses some packets  resulting in jerky trajectories.
Sending the packet multiple times (calling multiple times function servoj_rt(...)) seams to fix the problem, but we would like to know if there is a more roboust and deterministic way of managing the situation.

Have you got any experience and suggestions with this situation?

We would also like to know if it is possible to use RTnet (http://www.rtnet.org/) with DRFL, in this way it will be possible to have a more reliable packets exchenge.
Can you provide some example (parameters, pragma instructions) to use rtNet on DRFL?

Many Thanks

**Comment by doosan-robotics** [comment]
Currently, when using real-time control, it is recommended to lower the delay time. We are planning improvements related to real-time control, but the exact date is undecided.
