### ISSUE TITLE
[단순문의]DRL Run 관련 문의

### ISSUE THREAD

**Issue by leejehak** [doosan-robotics/API-DRFL#14]
DRL로 작성한 파일을 TaskWriter에서 불러와 실행하면 명령이 TCP/IP 를 통해 전달되는게 프로그램이 메모리상에서 바로 실행되는 것이 맞나요?(응답성 관련)

**Comment by doosan-robotics** [comment]
내부 PC에서 실행을 시키든 / 외부 PC에서 실행을 시키든 응답성에 유의미한 차이는 없습니다.
