### ISSUE TITLE
System Exception: cannot signal semaphore

### ISSUE THREAD

**Issue by Promation** [doosan-robotics/API-DRFL#16]
At multiple customers we are using an API application, running on a windows PC, to control the robot from an external controller. 
We started from the example program (main.cpp) provided by Doosan, which we altered and expanded to suit our needs.

We have gotten multiple reports from these customers that the application crashes and outputs the following message: "System Exception: cannot signal semaphore"
See image at the bottom.

Given the rarity and (seemingly) randomness of the exception, we have not been able to reproduce it in an IDE.

I found following issue online describing the same error: https://bytemeta.vip/repo/doosan-robotics/doosan-robot/issues/89
Is there more known about under which circumstances this exception occurs?

Thank you in advance.

![IMG_2263 jpg](https://user-images.githubusercontent.com/118969916/203762691-7c373fa0-6070-4218-908a-158520c39e75.png)

**Comment by Promation** [comment]
If I understand correctly, a computer with a slower CPU has more chance to get this error?

**Comment by doosan-robotics** [comment]
@Promation 
There could be various reasons. However, since the cause is in the internal socket processing thread, it is important to reduce the delay inside the callback function.
If you are still having problems, please show me an example file.

**Comment by doosan-robotics** [comment]
@Promation 
Please reopen the issue for further inquiries.
