### ISSUE TITLE
Changelog not updated

### ISSUE THREAD

**Issue by gabri202** [doosan-robotics/API-DRFL#18]
Hi,I was scrolling in the manual and the changelog stops at 1.27 version of the 2022-07-04.
There were several updates from that date, but no new changelog was added after that, could you update the file with latest changes? It would help a lot.

**Comment by doosan-robotics** [comment]
@gabri202 
Updated new manual on 02/21.

Please download and check the new Binary through Doosan Robotics Robot Lab.

https://robotlab.doosanrobotics.com/ko/board/Resources/Software/4dad8b7f-8331-ec11-b6e6-00224858dac4?pageId=3998f0c6-5845-e911-a827-000d3a07fb97&searchKeyword=

**Comment by doosan-robotics** [comment]
@gabri202 
Please reopen the issue for further inquiries.
