### ISSUE TITLE
"undefined reference to [function name]" errors

### ISSUE THREAD

**Issue by YoungsunKwon** [doosan-robotics/API-DRFL#19]
My system is Ubuntun 20.04.  In this .zip file, there is an example file called main.cpp (under BINARY_GL010117_20230206A/example/linux_xenomai).  When I try to compile the program with this command:

g++ -g -Wall -L/home/cindy/Doosan/BINARY_GL010117_20230206A/library/Linux/64bits/20.04 -I/home/cindy/Doosan/BINARY_GL010117_20230206A/include -lDRFL main.cpp

I get lots of "undefined reference to [function name]" errors, for example, below is some log from running this g++ command:

/usr/bin/ld: /tmp/cc7gVtm0.o: in function `DRAFramework::CDRFLEx::set_digital_output(GPIO_CTRLBOX_DIGITAL_INDEX, bool)':
/home/cindy/Doosan/BINARY_GL010117_20230206A/include/DRFLEx.h:718: undefined reference to `_set_digital_output'
/usr/bin/ld: /tmp/cc7gVtm0.o: in function `DRAFramework::CDRFLEx::set_safety_mode(SAFETY_MODE, SAFETY_MODE_EVENT)':
/home/cindy/Doosan/BINARY_GL010117_20230206A/include/DRFLEx.h:792: undefined reference to `_set_safety_mode'
/usr/bin/ld: /tmp/cc7gVtm0.o: in function `DRAFramework::CDRFLEx::setup_monitoring_version(int)':
/home/cindy/Doosan/BINARY_GL010117_20230206A/include/DRFLEx.h:856: undefined reference to `_setup_monitoring_version'

When I check the code, I find that the function in DRFLEx.h starts with "_"  only has a declaration, but there is no corresponding definition.  Hence I am hitting the "undefined reference" error.

I also checked your github repo (https://secure-web.cisco.com/1vkfAxuhiZlGtka-R-o2GXnYapbH2BY3_3lYdGnH34nS446-Utrtmb1_AOy7_5xC-FPy4sma5nqs9KHtXCdzcNOdWmtQz9497LvnlPW1A_OZNexGfzmw8vKqC7vM0wNVJSLjkdGUkr8hEeNyPHf47BawIljlBTiVPhh7QSlHIOAO1J9C2VeYrnwmL8r2XfOzNrM7N4YV8iWTcfzuy6ma7T4Dj1Bbsx6ErOIjIHwCwaitHMWmhWuJAZ7oBUBJNeKGvDn_nK4_4v07tUrya9NuBIlxpVTNdKcx_M05rQI1XOC7DOYhiRqBIyVp_B2bBkZso/https%3A%2F%2Fgithub.com%2Fdoosan-robotics%2Fdoosan-robot%2Ftree%2Fmaster%2Fcommon) but also could not find the corresponding definition either.

Could you please help:
1. How to compile/run these example cpp files from this zip file downloaded from your website?
2. I assume once (1) is solved, I run these examples by connecting my laptop to the robot arm.  Is that true?  If not, how can I use these examples to control the arm/get the information from the arm?  If so, is there any setup I need to do or any document that I can follow?

**Comment by kong2983** [comment]
_ 접두사가 붙은 함수는 C 함수를 의미합니다. 저희 DRFL 구조 상에서 C 함수는 라이브러리 파일(windows의 경우 dll, linux의 경우 .a 파일)을 참조하여 함수를 실행합니다. 라이브러리 위치를 찾지 못하여 undefined reference 에러가 발생하는 것으로 추정됩니다.

**Comment by cindyysi** [comment]
@kong2983 Thank you for the reply.  I also assume this problem is coming from when the library could not be found.  But I am not sure how to compile and run the example.cpp file even I "think" I have put the library path in my command.  Can you please advise on it?

This is the structure of my directory:

```
-- Doosan/
  -- example/
     -- linux_xenomai/
         -- main.cpp
  
  -- include/
     -- DRFC.h  DRFLEx.h  DRFL.h  DRFS.h
  
  -- library/
     -- Linux/
         -- 64bits/
             -- 20.04/
                 -- libDRFL.a  libPocoFoundation.so.62  libPocoNet.so.62
```

Under the `/Doosan/example/linux_xenoma` directory, I run this command to compile the main.cpp file: 
`g++ -g -Wall -L/home/cindy/Doosan/library/Linux/64bits/20.04 -I/home/cindy/Doosan/include -lDRFL main.cpp`
I put the absolute path to the library and include files in `-L` and `-I` and I also add the library as `-lDRFL`.  Can you please suggest what command I should use such that I can successfully compile and run the main.cpp program?  Thank you so much!  cc @YoungsunKwon

**Comment by doosan-robotics** [comment]
@cindyysi 
Please check the environment below.
Ubuntu 20.04 LTS
x86_64 architecture
If your environment is correct, try the following.
First of all we need to modify main.cpp . main.cpp attached to the example is for Windows and contains functions that cannot be used in Linux.

1. Build with g++ in the linux_xenomai directory

**g++ -c main.cpp**

2. If main.o is created normally, enter the command below to create an example file

**g++ -o g++ -o drfl_tets main.o ../../library/Linux/64bits/20.04/libDRFL.a /usr/lib/libPocoFoundation.so /usr/lib/libPocoNet.so**

The command references the poco library from the apt repository. The Poco library can be downloaded with the command below.

**sudo apt-get install libpoco-dev**

3. Check the build. When the build is complete, test the actual controller and connection.

Build examples (windows, linux) including the above examples will be uploaded to git soon.
Please let me know if there is any problem

thank you

@YoungsunKwon

**Comment by cindyysi** [comment]
Thank you for the help @YoungsunKwon!  I am able to build the example `main.cpp` file after following your steps.  One thing I notice is that installing `libpoco-dev` does not allow me to successfully get `drfl_test`.  What I need to do is to create symbolic links for both `libPocoFoundation.so` and `libPocoNet.so` that are under the `/library/Linux/64bits/20.04/` such that they are both accessible from `/usr/lib`

**Comment by doosan-robotics** [comment]
@cindyysi 
We recommend using the poco library installed through libpoco-dev. The poco library included in our distribution file is a consideration for those who have an unstable download environment.
