### ISSUE TITLE
Error in compiling the real-time example code for Windows

### ISSUE THREAD

**Issue by kamikaze-46** [doosan-robotics/API-DRFL#20]
We are trying to test the Realtime API commands using the Realtime example code for windows provided by Doosan. But we are getting multiple errors while compiling it using Visual studio 2022 as shown below.

![image](https://user-images.githubusercontent.com/120707473/226356743-604c7a8a-2dcc-4405-b585-22ec6b9ea9dd.png)

Visual Studio Project link: https://vyuti-my.sharepoint.com/:u:/g/personal/kaifali_bhojani_cynlr_com/EbYtAs_PMstFlCdEtwfvyXsBtspZxPeuZn6tXfuu7AzLEg?e=kSlARa

Realtime API example - https://vyuti-my.sharepoint.com/:f:/g/personal/kaifali_bhojani_cynlr_com/EkewlqeIeVJJtNWMl92h7HoBM67jawtYjEKtMHhJOuuTEA?e=BqBa7J

Our motive is to use the Realtime API commands on Windows OS to control the robot and get the feedback in real-time.

**Comment by doosan-robotics** [comment]
@kamikaze-46 
Our realtime example was tested in the xenomai environment (functions in the example are supported by xenomai2).
Not tested in Windows environment. I recommend using the normal servoj command if you are okay with it. A typical servoj command guarantees a latency of around 50 ms.

**Comment by doosan-robotics** [comment]
@kamikaze-46 
If there are no further inquiries,  close the issue.
