### ISSUE TITLE
Library file that supports Ubuntu 22.04

### ISSUE THREAD

**Issue by domire8** [doosan-robotics/API-DRFL#31]
Hi,
We've been using the DRFL library for realtime velocity control recently, and it works quite fine. However, we deploy our applications usually on Ubuntu 22.04 and the library file for 22.04 is currently not provided.

Are there plans to release the DRFL library for 22.04 soon or if not, could we request that? It would be great to support the most recent version of Ubuntu too.

**Comment by kirillmorozov** [comment]
Hi Dominic, I've already asked for that in #11 but the answer was:

> There are currently no plans for that matter.

**Comment by kirillmorozov** [comment]
By the time they'll do that Ubuntu 24.04 will already be released.

**Comment by doosan-robotics** [comment]
Dear @domire8 @kirillmorozov @nnbutler @kirillmorozov ,

I am sorry for the late reply. We've updated DRFL version with supporting ubuntu 22.04 and arm.
Please check the new features as below 
https://manual.doosanrobotics.com/en/api/1.31/Publish/

**Comment by domire8** [comment]
> By the time they'll do that Ubuntu 24.04 will already be released.

This is quite relevant now..
