### ISSUE TITLE
DRFL library on AMR architecture 

### ISSUE THREAD

**Issue by RomaricGo** [doosan-robotics/API-DRFL#45]
Hello, I try to run doosan-robot2 on a virtual machine with Ubuntu but the  DRFL only works on the x86 architecture.

do you plan to release a library compatible with ARM architecture? Is it possible to get source code of the API?

Thank you for your support

**Comment by doosan-robotics** [comment]
Dear @RomaricGo ,

We are happy to announce adding DRFL for ARM architecture. Please check the latest version DRFL
