### ISSUE TITLE
What the correct way of telling the robot which payload it carries?

### ISSUE THREAD

**Issue by kirillmorozov** [doosan-robotics/API-DRFL#5]
Suppose I have a H0217 robot that's picking a 10kg box.
Which methods from DRFL API do I need to call and in which order to tell the robot that it's now carrying a 10kg box?

**Comment by doosan-robotics** [comment]
The case seems to be a robot-related problem, not an API usage problem. I will contact technical sales.

**Comment by doosan-robotics** [comment]
Through the get_workpiece_weight command, you can automatically measure the weight of the current work piece.

**Comment by kirillmorozov** [comment]
Okay, `get_workpiece_weight` returned the weight of the payload as a `float`. How do I apply it? Which methods in which order and with what arguments do I need to call?

**Comment by doosan-robotics** [comment]
sorry. I misunderstood. You can set the tool weight you want by using the add_tool command.

**Comment by kirillmorozov** [comment]
Are you suggesting that I need to create a new tool each time robot's payload changes?

And what the `set_workpiece_weight`?

Which of these methods is preferable when it comes to settings the robot's payload?

I'm asking these questions because there's no example in the documentation.

**Comment by doosan-robotics** [comment]
@kirillmorozov 
You can use set_workpiece_weight to set the weight of the workpiece. Alternatively, you can use set_tool to alternately set the state of not holding the workpiece / the state of holding the workpiece.

sorry for the late reply

**Comment by doosan-robotics** [comment]
@kirillmorozov 
Please reopen the issue for further inquiries.
