### ISSUE TITLE
Which user speed limit clamps `moves` motions?

### ISSUE THREAD

**Issue by kirillmorozov** [doosan-robotics/API-DRFL#6]
When I'm trying to execute a spline motion I always get the following SYSINFO alarm:

```
2.1214 - Resulting target speed to complete present motion within the given motion duration exceeds user speed limit (motion duration shall be adjusted to meet user speed limit) | [INFO]finalTime(16.652) is adjusted above User Input(3.961)
```

When I've tried to set all speed limit to robot's max possible speed, finalTime was still adjusted to the same value. But when I've set TCP speed limit to 100mm/s I still got the alarm and immediately after a SYSWARN:

```
2.9014 - TCP speed has exceeded user limit. | mode=Normal, limit speed=100.000(mm/s)[3.93701(in/s)], cur_speed=100.063(mm/s)[3.93948(in/s)]
```

So which user limit affects spline finalTime adjustment and how?

**Comment by doosan-robotics** [comment]
I will contact the algorithm team.

**Comment by doosan-robotics** [comment]
@kirillmorozov 
Looking at the logs, it appears that it is already moving at full speed.
What's wrong with spline motion? We can also add servo motion etc. if needed.
