### ISSUE TITLE
[API] API 기술문의에 관련 건 - Digital I/O 기능

### ISSUE THREAD

**Issue by Yun-SeongHun** [doosan-robotics/API-DRFL#7]
[문의 내용]

Digital I/O 에 대한 기능을 변경하여 Joy-con 등과 연결하여 협동로봇의 상하좌우 전진 후진 등의 제어를 하려 합니다.(Z축 Y축 등)

이에 대한 API 설정이 가능한지 궁금하여 질문드려봅니다.

감사합니다

**Comment by doosan-robotics** [comment]
Digital Input을 통한 Jog 기능은 지원하지 않고 있습니다. ROS를 사용하는 것을 추천드립니다.
